version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sm
      POSTGRES_PASSWORD: sm
      POSTGRES_DB: sm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sm"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: {}
